name: Auto Update ShapeEngine Documentation

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  repository_dispatch:
    types: [trigger-docs-update]

jobs:
  build-and-update-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ShapeEngineDocs
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Clone ShapeEngine repository
        run: |
          git clone https://github.com/DaveGreen-Games/ShapeEngine.git ../ShapeEngine

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x' # Use the version matching your DocFX

      - name: Install DocFX
        run: |
          dotnet tool update -g docfx

      - name: Generate Documentation
        run: |
          docfx docfx.json

      - name: Commit & Push Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git diff --cached --quiet || git commit -m "Automated update of ShapeEngine docs"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}